### ISSUE TITLE
Use Spotless plugin to help enforce basic formatting / license

### ISSUE THREAD

**Issue by simonbasle** [reactor/reactor#700]
See https://github.com/diffplug/spotless/tree/main/plugin-gradle#-spotless-plugin-for-gradle

The configuration that was found while experimenting with this in reactor/reactor-core#2726 is as follows:

```groovy
spotless {
	if (project.hasProperty("spotlessFrom")) {
		println "[Spotless] Ratchet from $project.spotlessFrom"
		ratchetFrom project.spotlessFrom
	}
	else if (isCiServer) {
		println "[Spotless] CI detected without explicit branch, not enforcing check"
		enforceCheck false
	}
	else {
		String spotlessBranch = "origin/3.3.x"
		println "[Spotless] Local run detected, ratchet from $spotlessBranch"
		ratchetFrom spotlessBranch
	}
	java {
		target '**/*.java'
		//the regexp below uses a non-greedy quantifier to find blocks of 4 spaces at beginning of line
		//it stops replacing such blocks with tabs once the first non-space character is found.
		//As such, 5 spaces are turned into a tab + one extra space, where greedy would have turned into space then tab.
		replaceRegex 'turn indentation 4 spaces into tabs', /^(\s*?)[ ]{4}(\s*)/, '$1\t$2'
		//the above can leave tabs-spaces-tabs occurrences (with less that 4 spaces). the regexp
		//below removes theses in-between spaces (again only looking at beginning of line)
		replaceRegex 'remove in-between spaces in indentation', /^(\t+)[ ]{1,3}(\t+)/, '$1$2'
		trimTrailingWhitespace()
		endWithNewline()
		licenseHeaderFile('codequality/spotless/licenseJava.txt')
		removeUnusedImports()
	}
}
```

It relies on the `-PspotlessFrom` to activate spotless on specific CI jobs, since spotless otherwise needs a full checkout of the project (in order to compare the commit with the relevant base branch).

Instead here we configure specific CI job to checkout everything and spotless to "ratchet from" the base branch of the PR:

```yaml
  spotless:
    name: spotless
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - uses: eskatos/gradle-command-action@v1
      name: gradle
      with:
        arguments: spotlessCheck -PspotlessFrom=origin/${{ github.base_ref }}
        wrapper-cache-enabled: true
        dependencies-cache-enabled: true
        configuration-cache-enabled: true
```
